### ISSUE TITLE
Package name for async storage needs updating

### ISSUE THREAD

**Issue by markymc** [leoafarias/use-state-persist#13]
Hi, thanks a lot for this library, it's super useful!

I wanted to let you know that without patching, this won't work on modern React Native setups as:

https://github.com/leoafarias/use-state-persist/blob/1219518273c5b1f9b917120b7ddf2b4809ed7959/src/storage/storage.native.ts#L1

Needs to be updated to:

`import AsyncStorage from '@react-native-async-storage/async-storage';`

Along with the `package.json` reference of course.

**Comment by leoafarias** [comment]
@markymc do you want to open a PR with the changes you propose.

**Comment by rastilho8** [comment]
> @markymc do you want to open a PR with the changes you propose.

Hi! The only thing you need to do is uninstall **@react-native-community/async-storage** and install **@react-native-async-storage/async-storage**. From what I see, all the methods are the same, they just changed the repository

**Comment by markymc** [comment]
Thanks guys. Sorry I was planning to come back to this and submit a PR later this month when I had time. 🙇‍♂️
