### ISSUE TITLE
Error: Sync Storage init() needs to be called. 

### ISSUE THREAD

**Issue by thegitparticle** [leoafarias/use-state-persist#8]
I did the basic implementation of setting the state using useStatePersist instead of the default useState hook after installing the package. 

The state is loading as usual (querying from API) but is not persisting, and on top of it, this error shows up whenever the screen is opened - "Error: Sync Storage init() needs to be called before using it."

**Comment by leoafarias** [comment]
@thegitparticle are you currently using it on react-native?

**Comment by thegitparticle** [comment]
@leoafarias Yes, React native running on Android 10.

**Comment by thegitparticle** [comment]
Hey, @leoafarias could you figure why this error?

**Comment by leoafarias** [comment]
@thegitparticle yes, will try to push an update over the weekend.

**Comment by thegitparticle** [comment]
Hi, were you able to find time to write the fix?

**Comment by leoafarias** [comment]
@thegitparticle sorry for the delay but there were some changes on the API. 
https://github.com/leoafarias/use-state-persist#react-native
Version 0.2.3 is available with the fix

**Comment by thegitparticle** [comment]
@leoafarias Hey, I tried calling it on top of the file, even in App.js but the error still keeps repeating - Sync Storage init() needs to be called before ....

Could you guide as to placing it where worked for you in your tests?

**Comment by franzejr** [comment]
@leoafarias I think this error is still happening on RN.

**Comment by franzejr** [comment]
@thegitparticle are you sure you added:

```
import { syncStorage } from 'use-state-persist'
syncStorage.init()
```

at the beginning of your RN project?  I just added and it worked, I dont get this error anymore.

**Comment by thegitparticle** [comment]
It's been a while I have tried this library. I might need it for a project next month. Maybe will try this you suggested then. thanks

**Comment by leoafarias** [comment]
Closing this issue updated the docs
